<?php
/**
 * ClimbingQuestionnaireApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Codealpine
 *
 * The codealpine API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ClimbingQuestionnaireApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ClimbingQuestionnaireApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for climbingQuestionnaireControllerFindAll
     *
     * .
     *
     */
    public function testClimbingQuestionnaireControllerFindAll()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for climbingQuestionnaireControllerFindForUser
     *
     * .
     *
     */
    public function testClimbingQuestionnaireControllerFindForUser()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for climbingQuestionnaireControllerFindOne
     *
     * .
     *
     */
    public function testClimbingQuestionnaireControllerFindOne()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for climbingQuestionnaireControllerGetAnalysisMessage
     *
     * .
     *
     */
    public function testClimbingQuestionnaireControllerGetAnalysisMessage()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for climbingQuestionnaireControllerSaveUserQuestionnaire
     *
     * .
     *
     */
    public function testClimbingQuestionnaireControllerSaveUserQuestionnaire()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
